# Generated by Django 3.0.7 on 2020-07-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipoTarefa', models.CharField(db_column='Tipo', max_length=64)),
                ('colab', models.ForeignKey(blank=True, db_column='ColaboradorUtilizadorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='utilizadores.Colaborador')),
            ],
            options={
                'db_table': 'Preferencia',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAtividade',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('atividade', models.ForeignKey(blank=True, db_column='Atividade', null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.Atividade')),
                ('preferencia', models.ForeignKey(blank=True, db_column='PreferenciaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='colaboradores.Preferencia')),
            ],
            options={
                'db_table': 'PreferenciaAtividade',
            },
        ),
        migrations.CreateModel(
            name='ColaboradorHorario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('inicio', models.TimeField(db_column='Inicio')),
                ('fim', models.TimeField(db_column='Fim')),
                ('colab', models.ForeignKey(blank=True, db_column='ColaboradorUtilizadorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='utilizadores.Colaborador')),
            ],
            options={
                'db_table': 'ColaboradorHorario',
            },
        ),
    ]
