# Generated by Django 3.0.7 on 2020-07-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, db_column='Sigla', max_length=32, null=True)),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, db_column='Sigla', max_length=32, null=True)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Diaaberto',
            fields=[
                ('precoalunos', models.FloatField(db_column='PrecoAlunos')),
                ('precoprofessores', models.FloatField(blank=True, db_column='PrecoProfessores', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('enderecopaginaweb', models.CharField(db_column='EnderecoPaginaWeb', max_length=255)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('emaildiaaberto', models.CharField(db_column='EmailDiaAberto', max_length=255)),
                ('ano', models.IntegerField(db_column='Ano')),
                ('datadiaabertoinicio', models.DateTimeField(db_column='DataDiaAbertoInicio')),
                ('datadiaabertofim', models.DateTimeField(db_column='DataDiaAbertoFim')),
                ('datainscricaoatividadesinicio', models.DateTimeField(db_column='DataInscricaoAtividadesInicio')),
                ('datainscricaoatividadesfim', models.DateTimeField(db_column='DataInscricaoAtividadesFim')),
                ('datapropostasatividadesincio', models.DateTimeField(db_column='DataPropostasAtividadesIncio')),
                ('dataporpostaatividadesfim', models.DateTimeField(db_column='DataPorpostaAtividadesFim')),
                ('escalasessoes', models.TimeField(db_column='EscalaSessoes')),
            ],
            options={
                'db_table': 'DiaAberto',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=64)),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='images/edifi')),
                ('campus', models.ForeignKey(db_column='Campus', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Campus')),
            ],
            options={
                'db_table': 'Edificio',
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255)),
                ('andar', models.CharField(blank=True, db_column='Andar', max_length=255)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('edificio', models.ForeignKey(blank=True, db_column='Edificio', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Edificio')),
            ],
            options={
                'db_table': 'Espaco',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('inicio', models.TimeField(db_column='Inicio')),
                ('fim', models.TimeField(db_column='Fim')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dia', models.DateField(db_column='Dia')),
                ('campus', models.ForeignKey(db_column='Campus', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Campus')),
                ('diaaberto', models.ForeignKey(db_column='diaAberto', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Diaaberto')),
                ('horarioid', models.ForeignKey(db_column='HorarioID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Horario')),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('identificador', models.CharField(db_column='Identificador', max_length=32)),
                ('dia', models.DateField(db_column='Dia')),
                ('diaaberto', models.ForeignKey(db_column='diaAberto', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Diaaberto')),
            ],
            options={
                'db_table': 'Transporte',
            },
        ),
        migrations.CreateModel(
            name='Transporteuniversitario',
            fields=[
                ('transporte', models.OneToOneField(db_column='Transporte', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='configuracao.Transporte')),
                ('capacidade', models.IntegerField(db_column='Capacidade')),
            ],
            options={
                'db_table': 'TransporteUniversitario',
            },
        ),
        migrations.CreateModel(
            name='Unidadeorganica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('sigla', models.CharField(db_column='Sigla', max_length=255)),
                ('campusid', models.ForeignKey(db_column='CampusID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Campus')),
            ],
            options={
                'db_table': 'UnidadeOrganica',
            },
        ),
        migrations.CreateModel(
            name='Transportehorario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('origem', models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Gambelas', 'Gambelas'), ('Penha', 'Penha')], db_column='Origem', max_length=32)),
                ('chegada', models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Gambelas', 'Gambelas'), ('Penha', 'Penha')], db_column='Chegada', max_length=32)),
                ('horaPartida', models.TimeField(db_column='HoraPartida')),
                ('horaChegada', models.TimeField(db_column='HoraChegada')),
                ('transporte', models.ForeignKey(db_column='Transporte', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Transporte')),
            ],
            options={
                'db_table': 'TransporteHorario',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacoedificio', models.CharField(db_column='EspacoEdificio', max_length=255)),
                ('espacoid', models.ForeignKey(db_column='EspacoID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Espaco')),
            ],
            options={
                'db_table': 'Sala',
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('prato', models.CharField(db_column='Prato', max_length=255)),
                ('tipo', models.CharField(choices=[('Carne', 'Carne'), ('Peixe', 'Peixe'), ('Vegetariano', 'Vegetariano'), ('Sobremesa', 'Sobremesa')], db_column='Tipo', max_length=255)),
                ('nrpratosdisponiveis', models.IntegerField(db_column='NrPratosDisponiveis')),
                ('menuid', models.ForeignKey(db_column='MenuID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Menu')),
            ],
            options={
                'db_table': 'Prato',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('sigla', models.CharField(blank=True, db_column='Sigla', max_length=255, null=True)),
                ('diaabertoid', models.ForeignKey(db_column='DiaAbertoID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Diaaberto')),
            ],
            options={
                'db_table': 'Idioma',
            },
        ),
    ]
