# Generated by Django 3.0.7 on 2020-07-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilizadores', '0001_initial'),
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaaberto',
            name='administradorutilizadorid',
            field=models.ForeignKey(db_column='AdministradorUtilizadorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilizadores.Administrador'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidadeorganicaid',
            field=models.ForeignKey(db_column='UnidadeOrganicaID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Unidadeorganica'),
        ),
        migrations.AddField(
            model_name='curso',
            name='unidadeorganicaid',
            field=models.ForeignKey(db_column='Unidadeorganica', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Unidadeorganica'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('campus', 'diaaberto', 'dia')},
        ),
    ]
