# Generated by Django 3.0.7 on 2024-03-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0006_auto_20240315_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportehorario',
            name='chegada',
            field=models.CharField(blank=True, choices=[('Gambelas', 'Gambelas'), ('Penha', 'Penha'), ('Terminal', 'Terminal')], db_column='Chegada', max_length=32),
        ),
        migrations.AlterField(
            model_name='transportehorario',
            name='origem',
            field=models.CharField(blank=True, choices=[('Gambelas', 'Gambelas'), ('Penha', 'Penha'), ('Terminal', 'Terminal')], db_column='Origem', max_length=32),
        ),
    ]
