# Generated by Django 3.0.7 on 2024-03-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0008_auto_20240315_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportehorario',
            name='chegada',
            field=models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Penha', 'Penha'), ('Gambelas', 'Gambelas')], db_column='Chegada', max_length=32),
        ),
        migrations.AlterField(
            model_name='transportehorario',
            name='origem',
            field=models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Penha', 'Penha'), ('Gambelas', 'Gambelas')], db_column='Origem', max_length=32),
        ),
    ]
