# Generated by Django 3.0.7 on 2024-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0010_auto_20240316_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportehorario',
            name='chegada',
            field=models.CharField(blank=True, choices=[('Penha', 'Penha'), ('Gambelas', 'Gambelas'), ('Terminal', 'Terminal')], db_column='Chegada', max_length=32),
        ),
        migrations.AlterField(
            model_name='transportehorario',
            name='origem',
            field=models.CharField(blank=True, choices=[('Penha', 'Penha'), ('Gambelas', 'Gambelas'), ('Terminal', 'Terminal')], db_column='Origem', max_length=32),
        ),
    ]
