# Generated by Django 3.0.7 on 2024-04-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0014_auto_20240415_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportehorario',
            name='chegada',
            field=models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Gambelas', 'Gambelas'), ('Penha', 'Penha')], db_column='Chegada', max_length=32),
        ),
        migrations.AlterField(
            model_name='transportehorario',
            name='origem',
            field=models.CharField(blank=True, choices=[('Terminal', 'Terminal'), ('Gambelas', 'Gambelas'), ('Penha', 'Penha')], db_column='Origem', max_length=32),
        ),
    ]
