# Generated by Django 3.0.7 on 2020-07-02 17:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
                ('valido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Utilizador',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.Utilizador')),
                ('gabinete', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Administrador',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.Utilizador')),
            ],
            options={
                'db_table': 'Participante',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorUniversitario',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.Utilizador')),
                ('gabinete', models.CharField(db_column='Gabinete', max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Departamento')),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Unidadeorganica')),
            ],
            options={
                'db_table': 'ProfessorUniversitario',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.Utilizador')),
                ('gabinete', models.CharField(db_column='Gabinete', max_length=255)),
                ('departamento', models.ForeignKey(db_column='DepartamentoID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Departamento')),
                ('faculdade', models.ForeignKey(db_column='FaculdadeID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Unidadeorganica')),
            ],
            options={
                'db_table': 'Coordenador',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('utilizador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utilizadores.Utilizador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Curso')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Departamento')),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Unidadeorganica')),
            ],
            options={
                'db_table': 'Colaborador',
            },
            bases=('utilizadores.utilizador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
