# Generated by Django 3.0.7 on 2020-07-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0005_auto_20200702_1848'),
        ('utilizadores', '0001_initial'),
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('estado', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
                ('colab', models.ForeignKey(blank=True, db_column='ColaboradorUtilizadorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilizadores.Colaborador')),
                ('coord', models.ForeignKey(db_column='CoordenadorUtilizadorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='utilizadores.Coordenador')),
                ('diaaberto', models.ForeignKey(db_column='Diaaberto', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Diaaberto')),
            ],
            options={
                'db_table': 'Tarefa',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='TarefaAcompanhar',
            fields=[
                ('tarefaid', models.OneToOneField(db_column='tarefaid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coordenadores.Tarefa')),
                ('origem', models.CharField(db_column='origem', max_length=255)),
                ('destino', models.CharField(db_column='destino', max_length=255)),
            ],
            options={
                'db_table': 'TarefaAcompanhar',
            },
        ),
        migrations.CreateModel(
            name='TarefaOutra',
            fields=[
                ('tarefaid', models.OneToOneField(db_column='tarefaid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coordenadores.Tarefa')),
                ('descricao', models.TextField(db_column='descricao')),
            ],
            options={
                'db_table': 'TarefaOutra',
            },
        ),
        migrations.CreateModel(
            name='TarefaAuxiliar',
            fields=[
                ('tarefaid', models.OneToOneField(db_column='tarefaid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coordenadores.Tarefa')),
                ('sessao', models.ForeignKey(db_column='sessao', on_delete=django.db.models.deletion.CASCADE, to='atividades.Sessao')),
            ],
            options={
                'db_table': 'TarefaAuxiliar',
            },
        ),
    ]
