# Generated by Django 3.0.7 on 2020-07-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes', '0001_initial'),
        ('coordenadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaacompanhar',
            name='inscricao',
            field=models.ForeignKey(db_column='inscricao', on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Inscricao'),
        ),
    ]
