# Generated by Django 3.0.7 on 2024-04-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0002_auto_20240415_0208'),
        ('configuracao', '0018_auto_20240418_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=False)),
                ('arquivado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('diaaberto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionarios', to='configuracao.Diaaberto')),
            ],
            options={
                'db_table': 'Questionario',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('escolhaMultipla', 'Escolha Múltipla'), ('inteiro', 'Inteiro'), ('porExtenso', 'Por Extenso')], default='extenso', max_length=30)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionario.Questionario')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='atividades.Tema')),
            ],
            options={
                'db_table': 'Pergunta',
            },
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_resposta', to='questionario.Pergunta')),
            ],
            options={
                'db_table': 'OpcaoResposta',
            },
        ),
    ]
