# Generated by Django 3.0.7 on 2024-04-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaQuestionario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tema', models.CharField(db_column='Tema', max_length=64)),
            ],
            options={
                'db_table': 'TemaQuestionario',
            },
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='questionario.TemaQuestionario'),
        ),
    ]
