# Generated by Django 3.0.7 on 2024-05-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_auto_20240419_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='arquivado',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='publicado',
        ),
        migrations.AddField(
            model_name='questionario',
            name='data_arquivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionario',
            name='data_validacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondida', models.BooleanField(default=False)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questionario.Questionario')),
            ],
            options={
                'db_table': 'Resposta',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('criado', 'Criado'), ('validado', 'Validado'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='criado', max_length=10)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_estados', to='questionario.Questionario')),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.AddField(
            model_name='questionario',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_estado', to='questionario.Estado'),
        ),
    ]
