# Generated by Django 3.0.7 on 2020-07-02 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0005_auto_20200702_1848'),
        ('utilizadores', '0001_initial'),
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Escola',
                'ordering': ['nome', 'local'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.BooleanField()),
                ('nalunos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ano', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('turma', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('areacientifica', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('dia', models.DateField()),
                ('meio_transporte', models.CharField(choices=[('comboio', 'Comboio'), ('autocarro', 'Autocarro'), ('outro', 'Meios Próprios')], max_length=40)),
                ('hora_chegada', models.TimeField(blank=True, null=True)),
                ('local_chegada', models.CharField(blank=True, max_length=200, null=True)),
                ('entrecampi', models.BooleanField(default=False)),
                ('diaaberto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Diaaberto')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Escola')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilizadores.Participante')),
            ],
            options={
                'db_table': 'Inscricao',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Inscricao')),
            ],
            options={
                'db_table': 'Responsavel',
            },
        ),
        migrations.CreateModel(
            name='Inscricaoprato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npratosalunos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('npratosdocentes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Campus')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Inscricao')),
            ],
            options={
                'db_table': 'InscricaoPrato',
            },
        ),
        migrations.CreateModel(
            name='Inscricaotransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npassageiros', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Inscricao')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao.Transportehorario')),
            ],
            options={
                'db_table': 'InscricaoTransporte',
                'unique_together': {('inscricao', 'transporte')},
            },
        ),
        migrations.CreateModel(
            name='Inscricaosessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nparticipantes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscricoes.Inscricao')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.Sessao')),
            ],
            options={
                'db_table': 'InscricaoSessao',
                'ordering': ['sessao__horarioid__inicio'],
                'unique_together': {('inscricao', 'sessao')},
            },
        ),
    ]
