# Generated by Django 3.0.7 on 2024-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nr_presentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='presenca',
            field=models.BooleanField(default=False),
        ),
    ]
