# Generated by Django 3.0.7 on 2024-04-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0001_initial'),
        ('configuracao', '0017_auto_20240415_0208'),
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('Atividade Laboratorial', 'Atividade Laboratorial'), ('Tertulia', 'Tertulia'), ('Palestra', 'Palestra'), ('Misto', 'Misto')], db_column='Tipo', default='Palestra', max_length=64),
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('ano', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coord', models.ForeignKey(db_column='CoordenadorUtilizadorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='utilizadores.Coordenador')),
                ('diaabertoid', models.ForeignKey(db_column='diaAbertoID', on_delete=django.db.models.deletion.CASCADE, to='configuracao.Diaaberto')),
                ('horarioid', models.ForeignKey(db_column='HorarioID', on_delete=django.db.models.deletion.DO_NOTHING, to='configuracao.Horario')),
            ],
            options={
                'db_table': 'Roteiro',
            },
        ),
        migrations.CreateModel(
            name='AtividadeRoteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.Atividade')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.Roteiro')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.Sessao')),
            ],
            options={
                'db_table': 'AtividadeRoteiro',
            },
        ),
    ]
