# Generated by Django 3.0.7 on 2024-04-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20240415_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividaderoteiro',
            name='sessao',
        ),
        migrations.RemoveField(
            model_name='roteiro',
            name='horarioid',
        ),
        migrations.AddField(
            model_name='atividaderoteiro',
            name='duracao',
            field=models.IntegerField(db_column='duracao', default=None, null=True),
        ),
        migrations.AddField(
            model_name='roteiro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='roteiroid',
            field=models.ForeignKey(db_column='RoteiroID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.Roteiro'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='atividadeid',
            field=models.ForeignKey(db_column='AtividadeID', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.Atividade'),
        ),
    ]
