# Generated by Django 3.0.7 on 2024-05-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_auto_20240423_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='nr_presentes',
            field=models.IntegerField(default=0),
        ),
    ]
