from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import os
from django.urls import reverse
from utilizadores.models import Participante
from utilizadores.tests.test_models import create_Participante_0
from notificacoes.tests.test_models import create_MensagemRecebida_0
from selenium.webdriver.support.wait import WebDriverWait
from dia_aberto.utils import get_driver


class LogoutTest(StaticLiveServerTestCase):
    """ Testes funcionais do logout - Sucesso """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.driver = get_driver()
        cls.driver.maximize_window()
        cls.driver.implicitly_wait(10)

    def setUp(self):
        self.participante = create_Participante_0()
        self.participante.set_password('andre123456')
        self.participante.save()

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()
        super().tearDownClass()

    def test_logout(self):
        """ Teste funcional de logout sucesso """
        self.driver.get('%s%s' % (self.live_server_url, reverse('home')))
        self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(By.ID, "id_username").send_keys(
            self.participante.username)
        self.driver.find_element(By.ID, "id_password").click()
        self.driver.find_element(By.ID, "id_password").send_keys("andre123456")
        self.driver.find_element(By.CSS_SELECTOR, ".is-outlined").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "a:nth-child(1) > .button").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".button > span:nth-child(2)").click()
        assert self.driver.find_element(
            By.CSS_SELECTOR, "p > strong").text == "Até á próxima!"


# # Generated by Selenium IDE
# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# class TestLogout():
#   def setup_method(self, method):
#     self.driver = webdriver.Firefox()
#     self.vars = {}

#   def teardown_method(self, method):
#     self.driver.quit()

#   def test_logout(self):
#     self.driver.get("http://127.0.0.1:8000/")
#     self.driver.set_window_size(1936, 1056)
#     self.driver.find_element(By.CSS_SELECTOR, ".icon").click()
#     self.driver.find_element(By.ID, "id_username").click()
#     self.driver.find_element(By.ID, "id_username").send_keys("admin")
#     self.driver.find_element(By.ID, "id_password").click()
#     self.driver.find_element(By.ID, "id_password").send_keys("admin")
#     self.driver.find_element(By.CSS_SELECTOR, ".is-outlined").click()
#     self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .button").click()
#     self.driver.find_element(By.CSS_SELECTOR, ".button > span:nth-child(2)").click()
#     assert self.driver.find_element(By.CSS_SELECTOR, "p > strong").text == "Até á próxima!"
