python manage.py makemigrations notificacoes
python manage.py makemigrations atividades
python manage.py makemigrations colaboradores
python manage.py makemigrations configuracao
python manage.py makemigrations coordenadores
python manage.py makemigrations inscricoes
python manage.py makemigrations notifications
python manage.py makemigrations auth
python manage.py makemigrations utilizadores
