# Generated by Django 3.0.7 on 2020-07-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificacoes', '0001_initial'),
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacaonotificacao',
            name='emissor',
            field=models.ForeignKey(db_column='emissorid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envia', to='utilizadores.Utilizador'),
        ),
        migrations.AddField(
            model_name='informacaonotificacao',
            name='recetor',
            field=models.ForeignKey(blank=True, db_column='recetorid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recebe', to='utilizadores.Utilizador'),
        ),
        migrations.AddField(
            model_name='informacaomensagem',
            name='emissor',
            field=models.ForeignKey(db_column='emissorid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envia_mensagem', to='utilizadores.Utilizador'),
        ),
        migrations.AddField(
            model_name='informacaomensagem',
            name='recetor',
            field=models.ForeignKey(blank=True, db_column='recetorid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recebe_mensagem', to='utilizadores.Utilizador'),
        ),
        migrations.AlterIndexTogether(
            name='notificacao',
            index_together={('recipient', 'unread')},
        ),
    ]
